const projects = [
  {
    id: 0,
    title: 'Techloom Solutions Pvt. Ltd',
    description: 'Elevate your online presence and drive digital growth with Techloom Solutions. Experience innovative web solutions crafted to perfection for businesses of all sizes.',
    githubLink: "https://github.com/Amankohare0514",
    liveLink: "https://techloomsolutions.tech/",
  },
  {
    id: 1,
    title: 'Reform',
    description: 'Create, customize, and share beautifully designed forms with Webflow?s user-friendly interface. This platform is ideal for prototyping and simplifying form creation with ease.',
    githubLink: "https://github.com/Amankohare0514/YourForm",
    liveLink: "https://your-form-15h1.vercel.app",
  },
  {
    id: 2,
    title: 'My Tube',
    description: 'Led the development of MyTube, a cutting-edge YouTube clone designed to provide a seamless video browsing experience with enhanced features for creators and viewers.',
    githubLink: "https://github.com/Amankohare0514/my_tube",
    liveLink: "https://my-tube-new.vercel.app/",
  },
  {
    id: 3,
    title: 'Student Management System',
    description: 'Developed a robust and scalable student management system. Users can efficiently manage student data, including reading, updating, and deleting information with ease.',
    githubLink: "https://github.com/Amankohare0514/Student_Management-System",
    liveLink: "https://student-management-software.vercel.app/",
  },
  {
    id: 4,
    title: 'Github Finder',
    description: 'GitHub Finder is a web application that allows users to search for GitHub profiles and repositories easily, providing a simple yet powerful user experience.',
    githubLink: "https://github.com/Amankohare0514/Github-Finder-with-styling",
    liveLink: "",
  },
  {
    id: 5,
    title: 'Right Draw',
    description: 'Right Draw is an innovative platform designed for creating and sharing whiteboards, providing users with infinite canvas experiences for creative collaboration and design.',
    githubLink: "https://github.com/Amankohare0514/RightDraw",
    liveLink: "https://right-draw.vercel.app/",
  },
  {
    id: 6,
    title: 'IMDB Clone',
    description: 'This IMDb clone offers a comprehensive database of movies, TV shows, and celebrity profiles. Users can explore detailed information and stay updated with the latest releases.',
    githubLink: "https://github.com/Amankohare0514/IMDB-CLONE",
    liveLink: "https://imdb-clone-lovat.vercel.app/",
  },
  {
    id: 7,
    title: 'Quiz-App',
    description: 'Quiz-App provides an engaging and interactive platform for users to test their knowledge across various topics, offering a fun and educational quiz-taking experience.',
    githubLink: "https://github.com/Amankohare0514/Quiz-App",
    liveLink: "https://quiz-app-flax-theta.vercel.app/",
  },
  {
    id: 8,
    title: "SnAx DaRk ThEme",
    description: "SnAx DaRk ThEme is a visually superior dark theme for code editors, surpassing popular themes like Ayu, Dracula, and Night Owl, designed for optimal code visibility.",
    githubLink: "https://marketplace.visualstudio.com/items?itemName=AmanKohare5.snax-dark-theme",
    liveLink: "https://marketplace.visualstudio.com/items?itemName=AmanKohare5.snax-dark-theme",
  },
];
export default projects;
